<script type="text/javascript" src="<?=base_url();?>js/jquery-1.11.2.min.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/bootstrap.min.js"></script>        
<script type="text/javascript" src="<?=base_url();?>js/SmoothScroll.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/jquery.scrollTo.min.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/jquery.localScroll.min.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/jquery.viewport.mini.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/jquery.countTo.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/jquery.appear.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/jquery.sticky.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/jquery.parallax-1.1.3.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/jquery.fitvids.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/owl.carousel.min.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/isotope.pkgd.min.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/imagesloaded.pkgd.min.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/jquery.magnific-popup.min.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/gmap3.min.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/wow.min.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/masonry.pkgd.min.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/jquery.simple-text-rotator.min.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/all.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/contact-form.js"></script>
<script type="text/javascript" src="<?=base_url();?>js/jquery.ajaxchimp.min.js"></script> 